// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RVPark_Team2.Data;

#nullable disable

namespace RVPark_Team2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421204032_SeedAllSitesAndTypes")]
    partial class SeedAllSitesAndTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = "Admin",
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            IsLocked = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$iLPVgQQZV5f3NI1gSGTKwuHrvT4iHnPVavbFn6f5AvGLj9eZBwrQi"
                        });
                });

            modelBuilder.Entity("Fee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Fees");
                });

            modelBuilder.Entity("RVPark_Team2.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfAdults")
                        .HasColumnType("int");

                    b.Property<bool>("Pets")
                        .HasColumnType("bit");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VehicleLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "test@example.com",
                            CustomerName = "John Doe",
                            EndDate = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = false,
                            NumberOfAdults = 0,
                            Pets = false,
                            SiteId = 1,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 150m
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "test@example.com",
                            CustomerName = "Jane Smith",
                            EndDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = false,
                            NumberOfAdults = 0,
                            Pets = false,
                            SiteId = 2,
                            StartDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 150m
                        },
                        new
                        {
                            Id = 3,
                            CustomerEmail = "test@example.com",
                            CustomerName = "Mike Johnson",
                            EndDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = false,
                            NumberOfAdults = 0,
                            Pets = false,
                            SiteId = 1,
                            StartDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 100m
                        },
                        new
                        {
                            Id = 4,
                            CustomerEmail = "test@example.com",
                            CustomerName = "Emily Davis",
                            EndDate = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = false,
                            NumberOfAdults = 0,
                            Pets = false,
                            SiteId = 3,
                            StartDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 150m
                        },
                        new
                        {
                            Id = 5,
                            CustomerEmail = "test@example.com",
                            CustomerName = "Chris Brown",
                            EndDate = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCancelled = true,
                            NumberOfAdults = 0,
                            Pets = false,
                            SiteId = 2,
                            StartDate = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 100m
                        });
                });

            modelBuilder.Entity("RVPark_Team2.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteTypeId");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SiteNumber = "1",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            SiteNumber = "2",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            SiteNumber = "3",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            SiteNumber = "4",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            SiteNumber = "5",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            SiteNumber = "6",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            SiteNumber = "7",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            SiteNumber = "8",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            SiteNumber = "9",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            SiteNumber = "10",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            SiteNumber = "11",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            SiteNumber = "11B",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            SiteNumber = "12",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            SiteNumber = "12B",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            SiteNumber = "13",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            SiteNumber = "14",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            SiteNumber = "15",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            SiteNumber = "17",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            SiteNumber = "18",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            SiteNumber = "19",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            SiteNumber = "20",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            SiteNumber = "21",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            SiteNumber = "22",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            SiteNumber = "23",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 25,
                            SiteNumber = "24",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            SiteNumber = "25",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            SiteNumber = "26",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            SiteNumber = "27",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 29,
                            SiteNumber = "28",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 30,
                            SiteNumber = "29",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            SiteNumber = "30",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            SiteNumber = "31",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 33,
                            SiteNumber = "C",
                            SiteTypeId = 1
                        },
                        new
                        {
                            Id = 34,
                            SiteNumber = "32",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 35,
                            SiteNumber = "33",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 36,
                            SiteNumber = "34",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 37,
                            SiteNumber = "35",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 38,
                            SiteNumber = "36",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 39,
                            SiteNumber = "37",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 40,
                            SiteNumber = "38",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 41,
                            SiteNumber = "39",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 42,
                            SiteNumber = "40",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 43,
                            SiteNumber = "41",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 44,
                            SiteNumber = "42",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 45,
                            SiteNumber = "43",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 46,
                            SiteNumber = "44",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 47,
                            SiteNumber = "45",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 48,
                            SiteNumber = "A",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 49,
                            SiteNumber = "B",
                            SiteTypeId = 2
                        },
                        new
                        {
                            Id = 50,
                            SiteNumber = "D-1",
                            SiteTypeId = 3
                        },
                        new
                        {
                            Id = 51,
                            SiteNumber = "D-2",
                            SiteTypeId = 3
                        },
                        new
                        {
                            Id = 52,
                            SiteNumber = "D-3",
                            SiteTypeId = 3
                        },
                        new
                        {
                            Id = 53,
                            SiteNumber = "D-4",
                            SiteTypeId = 3
                        },
                        new
                        {
                            Id = 54,
                            SiteNumber = "D-5",
                            SiteTypeId = 3
                        },
                        new
                        {
                            Id = 55,
                            SiteNumber = "D-6",
                            SiteTypeId = 3
                        },
                        new
                        {
                            Id = 56,
                            SiteNumber = "D-7",
                            SiteTypeId = 3
                        },
                        new
                        {
                            Id = 57,
                            SiteNumber = "T-1",
                            SiteTypeId = 4
                        });
                });

            modelBuilder.Entity("RVPark_Team2.Models.SitePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("SitePhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhotoUrl = "/images/site1MapPhoto.png",
                            SiteId = 1
                        },
                        new
                        {
                            Id = 2,
                            PhotoUrl = "/images/site1Photo1.jpg",
                            SiteId = 1
                        });
                });

            modelBuilder.Entity("RVPark_Team2.Models.SiteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Standard back-in RV site",
                            Name = "Back-In"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Standard pull-through RV site",
                            Name = "Pull-Through"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dry camping site with no hook-ups",
                            Name = "Dry"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tent-only camping site",
                            Name = "Tent"
                        });
                });

            modelBuilder.Entity("RVPark_Team2.Models.SiteTypePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiteTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SiteTypeId");

                    b.ToTable("SiteTypePricings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 35.00m,
                            SiteTypeId = 1,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Price = 35.00m,
                            SiteTypeId = 2,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Price = 25.00m,
                            SiteTypeId = 3,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Price = 25.00m,
                            SiteTypeId = 4,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Fee", b =>
                {
                    b.HasOne("RVPark_Team2.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("RVPark_Team2.Models.Site", b =>
                {
                    b.HasOne("RVPark_Team2.Models.SiteType", "SiteType")
                        .WithMany("Sites")
                        .HasForeignKey("SiteTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SiteType");
                });

            modelBuilder.Entity("RVPark_Team2.Models.SitePhoto", b =>
                {
                    b.HasOne("RVPark_Team2.Models.Site", "PSite")
                        .WithMany("Photos")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PSite");
                });

            modelBuilder.Entity("RVPark_Team2.Models.SiteTypePrice", b =>
                {
                    b.HasOne("RVPark_Team2.Models.SiteType", "SiteType")
                        .WithMany("Prices")
                        .HasForeignKey("SiteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteType");
                });

            modelBuilder.Entity("RVPark_Team2.Models.Site", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("RVPark_Team2.Models.SiteType", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
